// <auto-generated />
namespace FiordilotoMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class credits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(credits));
        
        string IMigrationMetadata.Id
        {
            get { return "201712201153020_credits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
